---
- name: Get list package
  uri:
    url: "{{ postgresql_url_repo_path }}/yum/{{ postgresql_version }}/{{ ansible_distribution.lower() }}/{% if ansible_distribution == 'Fedora' %}{{ ansible_distribution.lower() }}{% else %}rhel{% endif %}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}"
    return_content: yes
  register: webpage
  run_once: true
  when: ansible_os_family == 'RedHat'

- name: Package name
  set_fact:
    package_name: "pgdg-{{ ansible_distribution.lower() }}{{ postgresql_version.split('.')|join('') }}-{{ postgresql_version }}"
  run_once: true
  when: ansible_os_family == 'RedHat'

- name: Search package
  set_fact:
    package_file_name: "{{ webpage.content|regex_search(package_name) }}"
  run_once: true
  when: ansible_os_family == 'RedHat'

- name: Debug variables
  debug: msg="{{ package_file_name }} {{ package_name }}"
  when: ansible_os_family == 'RedHat'

- name: Manage repo package
  package:
    name: "{{ postgresql_url_repo_path }}/yum/{{ postgresql_version }}/{{ ansible_distribution.lower() }}/{% if ansible_distribution == 'Fedora' %}{{ ansible_distribution.lower() }}{% else %}rhel{% endif %}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}/{{ package_file_name }}"
    state: "{{ postgresql_url_repo_state }}"
  when: ansible_os_family == 'RedHat'

- name: Add an Apt signing key
  apt_key:
    id: "{{ postgresql_url_repo_key }}"
    url: "{{ postgresql_url_repo_path }}/apt/{{ postgresql_url_repo_key }}.asc"
    state: "{{ postgresql_url_repo_state }}"
  when: ansible_os_family == 'Debian'

- name: Add an Apt repository
  apt_repository:
    repo: "deb {{ postgresql_url_repo_path }}/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: "{{ postgresql_url_repo_state }}"
  when: ansible_os_family == 'Debian'

# Extend availables version postgresql from official repos:
# RHEL/CentOS/SL/OL 7 9.2+
# RHEL/CentOS/SL/OL 6 8.4+
# Debian 7 9.1+
# Debian 8 8.4+
# Debian 9 9.2+
# Ubuntu 14 8.4+
# Ubuntu 16 9.1+
# Ubuntu 18 9.3+
