---
- name: Get list package
  uri:
    url: "{{ postgresql_url_repo_path }}/yum/{{ postgresql_version }}/{{ ansible_os_family.lower() }}/{% if ansible_distribution == 'Fedora' %}{{ ansible_distribution.lower() }}{% else %}rhel{% endif %}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}"
    return_content: yes
  register: webpage
  run_once: true
  when: ansible_os_family == 'RedHat'

- name: Package name
  set_fact:
    package_name: "pgdg-{{ ansible_distribution.lower() }}-{{ __local_postgresql_version_str.split('.')|join('') }}-{{ postgresql_version }}-\\d+\\.noarch\\.rpm"
  run_once: true
  when: ansible_os_family == 'RedHat'

- name: Search package
  set_fact:
    package_file_name: "{{ webpage.content|regex_search(package_name) }}"
  run_once: true
  when: ansible_os_family == 'RedHat'

- name: Manage repo package
  package:
    name: "{{ postgresql_url_repo_path }}/yum/{{ postgresql_version }}/{{ ansible_os_family.lower() }}/{% if ansible_distribution == 'Fedora' %}{{ ansible_distribution.lower() }}{% else %}rhel{% endif %}-{{ ansible_distribution_version.split('.')[0] }}-{{ ansible_architecture }}/{{ package_file_name }}"
    state: "{{ postgresql_url_repo_state }}"
  when: ansible_os_family == 'RedHat'

- name: Install https transport for apt
  package:
    name: apt-transport-https
    state: present
  when: ansible_os_family == 'Debian'

- name: Add an Apt signing key
  apt_key:
    id: "{{ postgresql_url_repo_key }}"
    url: "{{ postgresql_url_repo_path }}/apt/{{ postgresql_url_repo_key }}.asc"
    state: "{{ postgresql_url_repo_state }}"
  when: ansible_os_family == 'Debian'

- name: Add an Apt repository
  apt_repository:
    repo: "deb {{ postgresql_url_repo_path }}/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: "{{ postgresql_url_repo_state }}"
  when: ansible_os_family == 'Debian'

# Extension available versions postgresql from official repos (some versions may be unsupported, but available for installation and use):
# RHEL/SL/OL/CentOS7 9.2+
# RHEL/SL/OL/CentOS6 8.4+
# Debian7 8.4+
# Debian8 8.4+
# Debian9 9.2+
# Ubuntu1404 8.4+
# Ubuntu1604 9.1+
# Ubuntu1804 9.3+
