---
# Variable configuration.
- name: Tasks for define and set variables.
  include_tasks: variables.yml

- name: Tasks for manage postgresql.org repositories.
  include_tasks: install_official_repo.yml
  when: install_official_repo is defined

# Setup/install tasks.
- name: OS setup/install tasks.
  include_tasks: setup-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- name: Tasks for initilisation database.
  include_tasks: initialize.yml

- name: Tasks for manage postgresql configuration.
  include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes
    sleep: 5

- name: Ensure PostgreSQL is running for Debian 7.
  shell: service {{ postgresql_daemon }} start
  args:
    warn: no
  when: ansible_distribution == 'Debian' and ansible_distribution_version.split('.')[0] == '7'

# Configure PostgreSQL.
- name: Tasks for manage databases.
  include_tasks: databases.yml
- name: Tasks for manage postgresql users.
  include_tasks: users.yml
