---
# Variable configuration.
- include_tasks: variables.yml

- include_tasks: install_official_repo.yml
  when: install_official_repo is defined

# Setup/install tasks.
- include_tasks: setup-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes

# Configure PostgreSQL.
- include_tasks: databases.yml
- include_tasks: users.yml
