---
# Variable configuration.
- name: Tasks for define and set variables.
  include_tasks: variables.yml
  tags:
    - config

- name: Tasks for manage postgresql.org repositories.
  include_tasks: install_official_repo.yml
  when: install_official_repo is defined

# Setup/install tasks.
- name: OS setup/install tasks.
  include_tasks: setup-{{ ansible_os_family }}.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- name: Tasks for initilization database.
  include_tasks: initialize.yml

- name: Tasks for manage postgresql configuration.
  include_tasks: configure.yml
  tags:
    - config

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes
  when: ( ansible_distribution.lower() + ansible_distribution_version.split('.')[0] != 'debian7' ) or ( ansible_distribution.lower() == 'ubuntu' and (((ansible_distribution_version.split('.')[0] + ansible_distribution_version.split('.')[1])|float)*100)|int > 1504 )

- name: Ensure PostgreSQL is started and enabled on boot ( for debian 7 and ubuntu lower 15.10 version ).
  service:
    name: "{{ postgresql_daemon }}"
    state: started
    enabled: yes
    sleep: 5
    args: "{{ postgresql_version }}"
  when: ( ansible_distribution.lower() + ansible_distribution_version.split('.')[0] == 'debian7' ) or ( ansible_distribution.lower() == 'ubuntu' and (((ansible_distribution_version.split('.')[0] + ansible_distribution_version.split('.')[1])|float)*100)|int < 151000 ) and install_official_repo is defined

- name: Ensure PostgreSQL is running for Debian 7 (not postgresql.org repo).
  shell: service {{ postgresql_daemon }} start
  args:
    warn: no
  when: ansible_distribution.lower() + ansible_distribution_version.split('.')[0] == 'debian7' and install_official_repo is not defined

# Configure PostgreSQL.
- name: Tasks for manage databases.
  include_tasks: databases.yml
  tags:
    - config

- name: Tasks for manage postgresql users.
  include_tasks: users.yml
  tags:
    - config
