---
- name: Ensure PostgreSQL packages are installed.
  package:
    name: "{{ item }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
  with_items: "{{ postgresql_packages }} + [ '{{ postgresql_python_library }}' ]"
