---
# Variable configuration.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: Define postgresql_version.
  set_fact:
    postgresql_version: "{{ __postgresql_version }}"
  when: postgresql_version is not defined

- name: Define postgres version specific variables for official repo.
  block:
  - name: Define postgresql_packages.
    set_fact:
      postgresql_packages: "{{ __default_postgres_vars['__' + postgresql_version].__postgresql_packages | list }}"
    when: postgresql_packages is not defined

  - name: Define postgresql_daemon.
    set_fact:
      postgresql_daemon: "{{ __default_postgres_vars['__' + postgresql_version].__postgresql_daemon }}"
    when: postgresql_daemon is not defined

  - name: Define postgresql_daemon ( for debian 7 and ubuntu lower 15.10 version).
    set_fact:
      postgresql_daemon: "{{ __postgresql_daemon }}"
    when: ( ansible_distribution.lower() + ansible_distribution_version.split('.')[0] == 'debian7' ) or ( ansible_distribution.lower() == 'ubuntu' and (((ansible_distribution_version.split('.')[0] + ansible_distribution_version.split('.')[1])|float)*100)|int < 151000 )

  - name: Debug vars
    debug: msg="{{ (((ansible_distribution_version.split('.')[0] + ansible_distribution_version.split('.')[1])|float)*100)|int }} < 1510"

  - name: Define postgresql_data_dir.
    set_fact:
      postgresql_data_dir: "{{ __default_postgres_vars['__' + postgresql_version].__postgresql_data_dir }}"
    when: postgresql_data_dir is not defined

  - name: Define postgresql_bin_path.
    set_fact:
      postgresql_bin_path: "{{ __default_postgres_vars['__' + postgresql_version].__postgresql_bin_path }}"
    when: postgresql_bin_path is not defined

  - name: Define postgresql_config_path.
    set_fact:
      postgresql_config_path: "{{ __default_postgres_vars['__' + postgresql_version].__postgresql_config_path }}"
    when: postgresql_config_path is not defined

  when: install_official_repo is defined

- name: Define postgres variables for OS or custom repositories.
  block:
  - name: Define postgresql_packages.
    set_fact:
      postgresql_packages: "{{ __postgresql_packages | list }}"
    when: postgresql_packages is not defined

  - name: Define postgresql_daemon.
    set_fact:
      postgresql_daemon: "{{ __postgresql_daemon }}"
    when: postgresql_daemon is not defined

  - name: Define postgresql_data_dir.
    set_fact:
      postgresql_data_dir: "{{ __postgresql_data_dir }}"
    when: postgresql_data_dir is not defined

  - name: Define postgresql_bin_path.
    set_fact:
      postgresql_bin_path: "{{ __postgresql_bin_path }}"
    when: postgresql_bin_path is not defined

  - name: Define postgresql_config_path.
    set_fact:
      postgresql_config_path: "{{ __postgresql_config_path }}"
    when: postgresql_config_path is not defined

  when: install_official_repo is not defined

- name: Set custom variables for PostgreSQL version lower than 9.3.
  set_fact:
    postgresql_hba_entries: []
    postgresql_global_config_options:
      - option: unix_socket_directory
        value: '{{ postgresql_unix_socket_directories[0] }}'
  when: (((postgresql_version|float)*10)|int <= 92 ) and (ansible_os_family.lower() + ansible_distribution_version.split('.')[0] != 'redhat7')
